public class HttpBasicCallout {
    
    
    public static HttpResponse doHttpCallout(){
    	
    	Http http = new Http();
		HttpRequest request = new HttpRequest();
		request.setEndpoint('https://postman-echo.com/get?foo1=bar1&foo2=bar2');
		request.setMethod('GET');
		HttpResponse response = http.send(request);
		
		system.debug('response------->'+response);
		
		return response;	
	
    }
    
}